
services:
  backend:
    build:
      context: ./iCognitus_test
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend-iCognitus
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge